// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

public interface DoubleValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.DoubleValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  double getValue();
}
