// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/type.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Enum}
 */
public final class Enum extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Enum)
    EnumOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Enum.class.getName());
  }
  // Use Enum.newBuilder() to construct.
  private Enum(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Enum() {
    name_ = "";
    enumvalue_ = java.util.Collections.emptyList();
    options_ = java.util.Collections.emptyList();
    syntax_ = 0;
    edition_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Enum_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Enum_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Enum.class, com.google.protobuf.Enum.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENUMVALUE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.EnumValue> enumvalue_;
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
    return enumvalue_;
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.EnumValueOrBuilder> 
      getEnumvalueOrBuilderList() {
    return enumvalue_;
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public int getEnumvalueCount() {
    return enumvalue_.size();
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.EnumValue getEnumvalue(int index) {
    return enumvalue_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.EnumValueOrBuilder getEnumvalueOrBuilder(
      int index) {
    return enumvalue_.get(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 4;
  private com.google.protobuf.SourceContext sourceContext_;
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   * @return Whether the sourceContext field is set.
   */
  @java.lang.Override
  public boolean hasSourceContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   * @return The sourceContext.
   */
  @java.lang.Override
  public com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }

  public static final int SYNTAX_FIELD_NUMBER = 5;
  private int syntax_ = 0;
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
   * @return The syntax.
   */
  @java.lang.Override public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }

  public static final int EDITION_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object edition_ = "";
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @return The edition.
   */
  @java.lang.Override
  public java.lang.String getEdition() {
    java.lang.Object ref = edition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      edition_ = s;
      return s;
    }
  }
  /**
   * <code>string edition = 6 [json_name = "edition"];</code>
   * @return The bytes for edition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEditionBytes() {
    java.lang.Object ref = edition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      edition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    for (int i = 0; i < enumvalue_.size(); i++) {
      output.writeMessage(2, enumvalue_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(3, options_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(5, syntax_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(edition_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, edition_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    for (int i = 0; i < enumvalue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, enumvalue_.get(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, options_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, syntax_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(edition_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, edition_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Enum)) {
      return super.equals(obj);
    }
    com.google.protobuf.Enum other = (com.google.protobuf.Enum) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getEnumvalueList()
        .equals(other.getEnumvalueList())) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (hasSourceContext() != other.hasSourceContext()) return false;
    if (hasSourceContext()) {
      if (!getSourceContext()
          .equals(other.getSourceContext())) return false;
    }
    if (syntax_ != other.syntax_) return false;
    if (!getEdition()
        .equals(other.getEdition())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getEnumvalueCount() > 0) {
      hash = (37 * hash) + ENUMVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getEnumvalueList().hashCode();
    }
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    if (hasSourceContext()) {
      hash = (37 * hash) + SOURCE_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSourceContext().hashCode();
    }
    hash = (37 * hash) + SYNTAX_FIELD_NUMBER;
    hash = (53 * hash) + syntax_;
    hash = (37 * hash) + EDITION_FIELD_NUMBER;
    hash = (53 * hash) + getEdition().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Enum parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Enum parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Enum parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Enum parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Enum parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Enum parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Enum prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.Enum}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Enum)
      com.google.protobuf.EnumOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Enum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Enum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Enum.class, com.google.protobuf.Enum.Builder.class);
    }

    // Construct using com.google.protobuf.Enum.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getEnumvalueFieldBuilder();
        getOptionsFieldBuilder();
        getSourceContextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      if (enumvalueBuilder_ == null) {
        enumvalue_ = java.util.Collections.emptyList();
      } else {
        enumvalue_ = null;
        enumvalueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      sourceContext_ = null;
      if (sourceContextBuilder_ != null) {
        sourceContextBuilder_.dispose();
        sourceContextBuilder_ = null;
      }
      syntax_ = 0;
      edition_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Enum_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Enum getDefaultInstanceForType() {
      return com.google.protobuf.Enum.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.protobuf.Enum build() {
      com.google.protobuf.Enum result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.protobuf.Enum buildPartial() {
      com.google.protobuf.Enum result = new com.google.protobuf.Enum(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.protobuf.Enum result) {
      if (enumvalueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          enumvalue_ = java.util.Collections.unmodifiableList(enumvalue_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.enumvalue_ = enumvalue_;
      } else {
        result.enumvalue_ = enumvalueBuilder_.build();
      }
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.protobuf.Enum result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sourceContext_ = sourceContextBuilder_ == null
            ? sourceContext_
            : sourceContextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.syntax_ = syntax_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.edition_ = edition_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.Enum) {
        return mergeFrom((com.google.protobuf.Enum)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Enum other) {
      if (other == com.google.protobuf.Enum.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (enumvalueBuilder_ == null) {
        if (!other.enumvalue_.isEmpty()) {
          if (enumvalue_.isEmpty()) {
            enumvalue_ = other.enumvalue_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureEnumvalueIsMutable();
            enumvalue_.addAll(other.enumvalue_);
          }
          onChanged();
        }
      } else {
        if (!other.enumvalue_.isEmpty()) {
          if (enumvalueBuilder_.isEmpty()) {
            enumvalueBuilder_.dispose();
            enumvalueBuilder_ = null;
            enumvalue_ = other.enumvalue_;
            bitField0_ = (bitField0_ & ~0x00000002);
            enumvalueBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEnumvalueFieldBuilder() : null;
          } else {
            enumvalueBuilder_.addAllMessages(other.enumvalue_);
          }
        }
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (other.hasSourceContext()) {
        mergeSourceContext(other.getSourceContext());
      }
      if (other.syntax_ != 0) {
        setSyntaxValue(other.getSyntaxValue());
      }
      if (!other.getEdition().isEmpty()) {
        edition_ = other.edition_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.EnumValue m =
                  input.readMessage(
                      com.google.protobuf.EnumValue.parser(),
                      extensionRegistry);
              if (enumvalueBuilder_ == null) {
                ensureEnumvalueIsMutable();
                enumvalue_.add(m);
              } else {
                enumvalueBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.google.protobuf.Option m =
                  input.readMessage(
                      com.google.protobuf.Option.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getSourceContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              syntax_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              edition_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.EnumValue> enumvalue_ =
      java.util.Collections.emptyList();
    private void ensureEnumvalueIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        enumvalue_ = new java.util.ArrayList<com.google.protobuf.EnumValue>(enumvalue_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.EnumValue, com.google.protobuf.EnumValue.Builder, com.google.protobuf.EnumValueOrBuilder> enumvalueBuilder_;

    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public java.util.List<com.google.protobuf.EnumValue> getEnumvalueList() {
      if (enumvalueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(enumvalue_);
      } else {
        return enumvalueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public int getEnumvalueCount() {
      if (enumvalueBuilder_ == null) {
        return enumvalue_.size();
      } else {
        return enumvalueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public com.google.protobuf.EnumValue getEnumvalue(int index) {
      if (enumvalueBuilder_ == null) {
        return enumvalue_.get(index);
      } else {
        return enumvalueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      if (enumvalueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnumvalueIsMutable();
        enumvalue_.set(index, value);
        onChanged();
      } else {
        enumvalueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder setEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      if (enumvalueBuilder_ == null) {
        ensureEnumvalueIsMutable();
        enumvalue_.set(index, builderForValue.build());
        onChanged();
      } else {
        enumvalueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(com.google.protobuf.EnumValue value) {
      if (enumvalueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnumvalueIsMutable();
        enumvalue_.add(value);
        onChanged();
      } else {
        enumvalueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue value) {
      if (enumvalueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnumvalueIsMutable();
        enumvalue_.add(index, value);
        onChanged();
      } else {
        enumvalueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        com.google.protobuf.EnumValue.Builder builderForValue) {
      if (enumvalueBuilder_ == null) {
        ensureEnumvalueIsMutable();
        enumvalue_.add(builderForValue.build());
        onChanged();
      } else {
        enumvalueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addEnumvalue(
        int index, com.google.protobuf.EnumValue.Builder builderForValue) {
      if (enumvalueBuilder_ == null) {
        ensureEnumvalueIsMutable();
        enumvalue_.add(index, builderForValue.build());
        onChanged();
      } else {
        enumvalueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder addAllEnumvalue(
        java.lang.Iterable<? extends com.google.protobuf.EnumValue> values) {
      if (enumvalueBuilder_ == null) {
        ensureEnumvalueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, enumvalue_);
        onChanged();
      } else {
        enumvalueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder clearEnumvalue() {
      if (enumvalueBuilder_ == null) {
        enumvalue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        enumvalueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public Builder removeEnumvalue(int index) {
      if (enumvalueBuilder_ == null) {
        ensureEnumvalueIsMutable();
        enumvalue_.remove(index);
        onChanged();
      } else {
        enumvalueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public com.google.protobuf.EnumValue.Builder getEnumvalueBuilder(
        int index) {
      return getEnumvalueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public com.google.protobuf.EnumValueOrBuilder getEnumvalueOrBuilder(
        int index) {
      if (enumvalueBuilder_ == null) {
        return enumvalue_.get(index);  } else {
        return enumvalueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public java.util.List<? extends com.google.protobuf.EnumValueOrBuilder> 
         getEnumvalueOrBuilderList() {
      if (enumvalueBuilder_ != null) {
        return enumvalueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(enumvalue_);
      }
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public com.google.protobuf.EnumValue.Builder addEnumvalueBuilder() {
      return getEnumvalueFieldBuilder().addBuilder(
          com.google.protobuf.EnumValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public com.google.protobuf.EnumValue.Builder addEnumvalueBuilder(
        int index) {
      return getEnumvalueFieldBuilder().addBuilder(
          index, com.google.protobuf.EnumValue.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.EnumValue enumvalue = 2 [json_name = "enumvalue"];</code>
     */
    public java.util.List<com.google.protobuf.EnumValue.Builder> 
         getEnumvalueBuilderList() {
      return getEnumvalueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.EnumValue, com.google.protobuf.EnumValue.Builder, com.google.protobuf.EnumValueOrBuilder> 
        getEnumvalueFieldBuilder() {
      if (enumvalueBuilder_ == null) {
        enumvalueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.EnumValue, com.google.protobuf.EnumValue.Builder, com.google.protobuf.EnumValueOrBuilder>(
                enumvalue_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        enumvalue_ = null;
      }
      return enumvalueBuilder_;
    }

    private java.util.List<com.google.protobuf.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        options_ = new java.util.ArrayList<com.google.protobuf.Option>(options_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> optionsBuilder_;

    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 3 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private com.google.protobuf.SourceContext sourceContext_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder> sourceContextBuilder_;
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     * @return Whether the sourceContext field is set.
     */
    public boolean hasSourceContext() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     * @return The sourceContext.
     */
    public com.google.protobuf.SourceContext getSourceContext() {
      if (sourceContextBuilder_ == null) {
        return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      } else {
        return sourceContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceContext_ = value;
      } else {
        sourceContextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(
        com.google.protobuf.SourceContext.Builder builderForValue) {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = builderForValue.build();
      } else {
        sourceContextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder mergeSourceContext(com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          sourceContext_ != null &&
          sourceContext_ != com.google.protobuf.SourceContext.getDefaultInstance()) {
          getSourceContextBuilder().mergeFrom(value);
        } else {
          sourceContext_ = value;
        }
      } else {
        sourceContextBuilder_.mergeFrom(value);
      }
      if (sourceContext_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public Builder clearSourceContext() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sourceContext_ = null;
      if (sourceContextBuilder_ != null) {
        sourceContextBuilder_.dispose();
        sourceContextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public com.google.protobuf.SourceContext.Builder getSourceContextBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getSourceContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    public com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
      if (sourceContextBuilder_ != null) {
        return sourceContextBuilder_.getMessageOrBuilder();
      } else {
        return sourceContext_ == null ?
            com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      }
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 4 [json_name = "sourceContext"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder> 
        getSourceContextFieldBuilder() {
      if (sourceContextBuilder_ == null) {
        sourceContextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder>(
                getSourceContext(),
                getParentForChildren(),
                isClean());
        sourceContext_ = null;
      }
      return sourceContextBuilder_;
    }

    private int syntax_ = 0;
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override public int getSyntaxValue() {
      return syntax_;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      syntax_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return The syntax.
     */
    @java.lang.Override
    public com.google.protobuf.Syntax getSyntax() {
      com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
      return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      syntax_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 5 [json_name = "syntax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      bitField0_ = (bitField0_ & ~0x00000010);
      syntax_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object edition_ = "";
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return The edition.
     */
    public java.lang.String getEdition() {
      java.lang.Object ref = edition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        edition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return The bytes for edition.
     */
    public com.google.protobuf.ByteString
        getEditionBytes() {
      java.lang.Object ref = edition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        edition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @param value The edition to set.
     * @return This builder for chaining.
     */
    public Builder setEdition(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      edition_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEdition() {
      edition_ = getDefaultInstance().getEdition();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string edition = 6 [json_name = "edition"];</code>
     * @param value The bytes for edition to set.
     * @return This builder for chaining.
     */
    public Builder setEditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      edition_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Enum)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Enum)
  private static final com.google.protobuf.Enum DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Enum();
  }

  public static com.google.protobuf.Enum getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Enum>
      PARSER = new com.google.protobuf.AbstractParser<Enum>() {
    @java.lang.Override
    public Enum parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Enum> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Enum> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Enum getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

