// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/type.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Field}
 */
public final class Field extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Field)
    FieldOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Field.class.getName());
  }
  // Use Field.newBuilder() to construct.
  private Field(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Field() {
    kind_ = 0;
    cardinality_ = 0;
    name_ = "";
    typeUrl_ = "";
    options_ = java.util.Collections.emptyList();
    jsonName_ = "";
    defaultValue_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Field_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Field_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Field.class, com.google.protobuf.Field.Builder.class);
  }

  /**
   * Protobuf enum {@code google.protobuf.Field.Kind}
   */
  public enum Kind
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TYPE_UNKNOWN = 0;</code>
     */
    TYPE_UNKNOWN(0),
    /**
     * <code>TYPE_DOUBLE = 1;</code>
     */
    TYPE_DOUBLE(1),
    /**
     * <code>TYPE_FLOAT = 2;</code>
     */
    TYPE_FLOAT(2),
    /**
     * <code>TYPE_INT64 = 3;</code>
     */
    TYPE_INT64(3),
    /**
     * <code>TYPE_UINT64 = 4;</code>
     */
    TYPE_UINT64(4),
    /**
     * <code>TYPE_INT32 = 5;</code>
     */
    TYPE_INT32(5),
    /**
     * <code>TYPE_FIXED64 = 6;</code>
     */
    TYPE_FIXED64(6),
    /**
     * <code>TYPE_FIXED32 = 7;</code>
     */
    TYPE_FIXED32(7),
    /**
     * <code>TYPE_BOOL = 8;</code>
     */
    TYPE_BOOL(8),
    /**
     * <code>TYPE_STRING = 9;</code>
     */
    TYPE_STRING(9),
    /**
     * <code>TYPE_GROUP = 10;</code>
     */
    TYPE_GROUP(10),
    /**
     * <code>TYPE_MESSAGE = 11;</code>
     */
    TYPE_MESSAGE(11),
    /**
     * <code>TYPE_BYTES = 12;</code>
     */
    TYPE_BYTES(12),
    /**
     * <code>TYPE_UINT32 = 13;</code>
     */
    TYPE_UINT32(13),
    /**
     * <code>TYPE_ENUM = 14;</code>
     */
    TYPE_ENUM(14),
    /**
     * <code>TYPE_SFIXED32 = 15;</code>
     */
    TYPE_SFIXED32(15),
    /**
     * <code>TYPE_SFIXED64 = 16;</code>
     */
    TYPE_SFIXED64(16),
    /**
     * <code>TYPE_SINT32 = 17;</code>
     */
    TYPE_SINT32(17),
    /**
     * <code>TYPE_SINT64 = 18;</code>
     */
    TYPE_SINT64(18),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        Kind.class.getName());
    }
    /**
     * <code>TYPE_UNKNOWN = 0;</code>
     */
    public static final int TYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>TYPE_DOUBLE = 1;</code>
     */
    public static final int TYPE_DOUBLE_VALUE = 1;
    /**
     * <code>TYPE_FLOAT = 2;</code>
     */
    public static final int TYPE_FLOAT_VALUE = 2;
    /**
     * <code>TYPE_INT64 = 3;</code>
     */
    public static final int TYPE_INT64_VALUE = 3;
    /**
     * <code>TYPE_UINT64 = 4;</code>
     */
    public static final int TYPE_UINT64_VALUE = 4;
    /**
     * <code>TYPE_INT32 = 5;</code>
     */
    public static final int TYPE_INT32_VALUE = 5;
    /**
     * <code>TYPE_FIXED64 = 6;</code>
     */
    public static final int TYPE_FIXED64_VALUE = 6;
    /**
     * <code>TYPE_FIXED32 = 7;</code>
     */
    public static final int TYPE_FIXED32_VALUE = 7;
    /**
     * <code>TYPE_BOOL = 8;</code>
     */
    public static final int TYPE_BOOL_VALUE = 8;
    /**
     * <code>TYPE_STRING = 9;</code>
     */
    public static final int TYPE_STRING_VALUE = 9;
    /**
     * <code>TYPE_GROUP = 10;</code>
     */
    public static final int TYPE_GROUP_VALUE = 10;
    /**
     * <code>TYPE_MESSAGE = 11;</code>
     */
    public static final int TYPE_MESSAGE_VALUE = 11;
    /**
     * <code>TYPE_BYTES = 12;</code>
     */
    public static final int TYPE_BYTES_VALUE = 12;
    /**
     * <code>TYPE_UINT32 = 13;</code>
     */
    public static final int TYPE_UINT32_VALUE = 13;
    /**
     * <code>TYPE_ENUM = 14;</code>
     */
    public static final int TYPE_ENUM_VALUE = 14;
    /**
     * <code>TYPE_SFIXED32 = 15;</code>
     */
    public static final int TYPE_SFIXED32_VALUE = 15;
    /**
     * <code>TYPE_SFIXED64 = 16;</code>
     */
    public static final int TYPE_SFIXED64_VALUE = 16;
    /**
     * <code>TYPE_SINT32 = 17;</code>
     */
    public static final int TYPE_SINT32_VALUE = 17;
    /**
     * <code>TYPE_SINT64 = 18;</code>
     */
    public static final int TYPE_SINT64_VALUE = 18;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Kind valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Kind forNumber(int value) {
      switch (value) {
        case 0: return TYPE_UNKNOWN;
        case 1: return TYPE_DOUBLE;
        case 2: return TYPE_FLOAT;
        case 3: return TYPE_INT64;
        case 4: return TYPE_UINT64;
        case 5: return TYPE_INT32;
        case 6: return TYPE_FIXED64;
        case 7: return TYPE_FIXED32;
        case 8: return TYPE_BOOL;
        case 9: return TYPE_STRING;
        case 10: return TYPE_GROUP;
        case 11: return TYPE_MESSAGE;
        case 12: return TYPE_BYTES;
        case 13: return TYPE_UINT32;
        case 14: return TYPE_ENUM;
        case 15: return TYPE_SFIXED32;
        case 16: return TYPE_SFIXED64;
        case 17: return TYPE_SINT32;
        case 18: return TYPE_SINT64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Kind>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Kind> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
            public Kind findValueByNumber(int number) {
              return Kind.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.protobuf.Field.getDescriptor().getEnumTypes().get(0);
    }

    private static final Kind[] VALUES = values();

    public static Kind valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Kind(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.Field.Kind)
  }

  /**
   * Protobuf enum {@code google.protobuf.Field.Cardinality}
   */
  public enum Cardinality
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CARDINALITY_UNKNOWN = 0;</code>
     */
    CARDINALITY_UNKNOWN(0),
    /**
     * <code>CARDINALITY_OPTIONAL = 1;</code>
     */
    CARDINALITY_OPTIONAL(1),
    /**
     * <code>CARDINALITY_REQUIRED = 2;</code>
     */
    CARDINALITY_REQUIRED(2),
    /**
     * <code>CARDINALITY_REPEATED = 3;</code>
     */
    CARDINALITY_REPEATED(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        Cardinality.class.getName());
    }
    /**
     * <code>CARDINALITY_UNKNOWN = 0;</code>
     */
    public static final int CARDINALITY_UNKNOWN_VALUE = 0;
    /**
     * <code>CARDINALITY_OPTIONAL = 1;</code>
     */
    public static final int CARDINALITY_OPTIONAL_VALUE = 1;
    /**
     * <code>CARDINALITY_REQUIRED = 2;</code>
     */
    public static final int CARDINALITY_REQUIRED_VALUE = 2;
    /**
     * <code>CARDINALITY_REPEATED = 3;</code>
     */
    public static final int CARDINALITY_REPEATED_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Cardinality valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Cardinality forNumber(int value) {
      switch (value) {
        case 0: return CARDINALITY_UNKNOWN;
        case 1: return CARDINALITY_OPTIONAL;
        case 2: return CARDINALITY_REQUIRED;
        case 3: return CARDINALITY_REPEATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cardinality>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Cardinality> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cardinality>() {
            public Cardinality findValueByNumber(int number) {
              return Cardinality.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.protobuf.Field.getDescriptor().getEnumTypes().get(1);
    }

    private static final Cardinality[] VALUES = values();

    public static Cardinality valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Cardinality(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.Field.Cardinality)
  }

  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_ = 0;
  /**
   * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
   * @return The kind.
   */
  @java.lang.Override public com.google.protobuf.Field.Kind getKind() {
    com.google.protobuf.Field.Kind result = com.google.protobuf.Field.Kind.forNumber(kind_);
    return result == null ? com.google.protobuf.Field.Kind.UNRECOGNIZED : result;
  }

  public static final int CARDINALITY_FIELD_NUMBER = 2;
  private int cardinality_ = 0;
  /**
   * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
   * @return The enum numeric value on the wire for cardinality.
   */
  @java.lang.Override public int getCardinalityValue() {
    return cardinality_;
  }
  /**
   * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
   * @return The cardinality.
   */
  @java.lang.Override public com.google.protobuf.Field.Cardinality getCardinality() {
    com.google.protobuf.Field.Cardinality result = com.google.protobuf.Field.Cardinality.forNumber(cardinality_);
    return result == null ? com.google.protobuf.Field.Cardinality.UNRECOGNIZED : result;
  }

  public static final int NUMBER_FIELD_NUMBER = 3;
  private int number_ = 0;
  /**
   * <code>int32 number = 3 [json_name = "number"];</code>
   * @return The number.
   */
  @java.lang.Override
  public int getNumber() {
    return number_;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 4 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_URL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object typeUrl_ = "";
  /**
   * <code>string type_url = 6 [json_name = "typeUrl"];</code>
   * @return The typeUrl.
   */
  @java.lang.Override
  public java.lang.String getTypeUrl() {
    java.lang.Object ref = typeUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string type_url = 6 [json_name = "typeUrl"];</code>
   * @return The bytes for typeUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeUrlBytes() {
    java.lang.Object ref = typeUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ONEOF_INDEX_FIELD_NUMBER = 7;
  private int oneofIndex_ = 0;
  /**
   * <code>int32 oneof_index = 7 [json_name = "oneofIndex"];</code>
   * @return The oneofIndex.
   */
  @java.lang.Override
  public int getOneofIndex() {
    return oneofIndex_;
  }

  public static final int PACKED_FIELD_NUMBER = 8;
  private boolean packed_ = false;
  /**
   * <code>bool packed = 8 [json_name = "packed"];</code>
   * @return The packed.
   */
  @java.lang.Override
  public boolean getPacked() {
    return packed_;
  }

  public static final int OPTIONS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int JSON_NAME_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object jsonName_ = "";
  /**
   * <code>string json_name = 10 [json_name = "jsonName"];</code>
   * @return The jsonName.
   */
  @java.lang.Override
  public java.lang.String getJsonName() {
    java.lang.Object ref = jsonName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonName_ = s;
      return s;
    }
  }
  /**
   * <code>string json_name = 10 [json_name = "jsonName"];</code>
   * @return The bytes for jsonName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonNameBytes() {
    java.lang.Object ref = jsonName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEFAULT_VALUE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object defaultValue_ = "";
  /**
   * <code>string default_value = 11 [json_name = "defaultValue"];</code>
   * @return The defaultValue.
   */
  @java.lang.Override
  public java.lang.String getDefaultValue() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      defaultValue_ = s;
      return s;
    }
  }
  /**
   * <code>string default_value = 11 [json_name = "defaultValue"];</code>
   * @return The bytes for defaultValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefaultValueBytes() {
    java.lang.Object ref = defaultValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      defaultValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kind_ != com.google.protobuf.Field.Kind.TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(1, kind_);
    }
    if (cardinality_ != com.google.protobuf.Field.Cardinality.CARDINALITY_UNKNOWN.getNumber()) {
      output.writeEnum(2, cardinality_);
    }
    if (number_ != 0) {
      output.writeInt32(3, number_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(typeUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, typeUrl_);
    }
    if (oneofIndex_ != 0) {
      output.writeInt32(7, oneofIndex_);
    }
    if (packed_ != false) {
      output.writeBool(8, packed_);
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(9, options_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jsonName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, jsonName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(defaultValue_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, defaultValue_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kind_ != com.google.protobuf.Field.Kind.TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, kind_);
    }
    if (cardinality_ != com.google.protobuf.Field.Cardinality.CARDINALITY_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, cardinality_);
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, number_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(typeUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, typeUrl_);
    }
    if (oneofIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, oneofIndex_);
    }
    if (packed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, packed_);
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, options_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(jsonName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, jsonName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(defaultValue_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, defaultValue_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Field)) {
      return super.equals(obj);
    }
    com.google.protobuf.Field other = (com.google.protobuf.Field) obj;

    if (kind_ != other.kind_) return false;
    if (cardinality_ != other.cardinality_) return false;
    if (getNumber()
        != other.getNumber()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getTypeUrl()
        .equals(other.getTypeUrl())) return false;
    if (getOneofIndex()
        != other.getOneofIndex()) return false;
    if (getPacked()
        != other.getPacked()) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (!getJsonName()
        .equals(other.getJsonName())) return false;
    if (!getDefaultValue()
        .equals(other.getDefaultValue())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (37 * hash) + CARDINALITY_FIELD_NUMBER;
    hash = (53 * hash) + cardinality_;
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getTypeUrl().hashCode();
    hash = (37 * hash) + ONEOF_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getOneofIndex();
    hash = (37 * hash) + PACKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPacked());
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (37 * hash) + JSON_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getJsonName().hashCode();
    hash = (37 * hash) + DEFAULT_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getDefaultValue().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Field parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Field parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Field prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Field)
      com.google.protobuf.FieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Field.class, com.google.protobuf.Field.Builder.class);
    }

    // Construct using com.google.protobuf.Field.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      kind_ = 0;
      cardinality_ = 0;
      number_ = 0;
      name_ = "";
      typeUrl_ = "";
      oneofIndex_ = 0;
      packed_ = false;
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      jsonName_ = "";
      defaultValue_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Field_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Field getDefaultInstanceForType() {
      return com.google.protobuf.Field.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.protobuf.Field build() {
      com.google.protobuf.Field result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.protobuf.Field buildPartial() {
      com.google.protobuf.Field result = new com.google.protobuf.Field(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.protobuf.Field result) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.protobuf.Field result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.kind_ = kind_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cardinality_ = cardinality_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.number_ = number_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.typeUrl_ = typeUrl_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.oneofIndex_ = oneofIndex_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.packed_ = packed_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.jsonName_ = jsonName_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.defaultValue_ = defaultValue_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.Field) {
        return mergeFrom((com.google.protobuf.Field)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Field other) {
      if (other == com.google.protobuf.Field.getDefaultInstance()) return this;
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      if (other.cardinality_ != 0) {
        setCardinalityValue(other.getCardinalityValue());
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTypeUrl().isEmpty()) {
        typeUrl_ = other.typeUrl_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getOneofIndex() != 0) {
        setOneofIndex(other.getOneofIndex());
      }
      if (other.getPacked() != false) {
        setPacked(other.getPacked());
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000080);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (!other.getJsonName().isEmpty()) {
        jsonName_ = other.jsonName_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getDefaultValue().isEmpty()) {
        defaultValue_ = other.defaultValue_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              kind_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              cardinality_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              number_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 50: {
              typeUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 50
            case 56: {
              oneofIndex_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 56
            case 64: {
              packed_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 64
            case 74: {
              com.google.protobuf.Option m =
                  input.readMessage(
                      com.google.protobuf.Option.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 82: {
              jsonName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 82
            case 90: {
              defaultValue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int kind_ = 0;
    /**
     * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override public int getKindValue() {
      return kind_;
    }
    /**
     * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.google.protobuf.Field.Kind getKind() {
      com.google.protobuf.Field.Kind result = com.google.protobuf.Field.Kind.forNumber(kind_);
      return result == null ? com.google.protobuf.Field.Kind.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.google.protobuf.Field.Kind value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Field.Kind kind = 1 [json_name = "kind"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      bitField0_ = (bitField0_ & ~0x00000001);
      kind_ = 0;
      onChanged();
      return this;
    }

    private int cardinality_ = 0;
    /**
     * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
     * @return The enum numeric value on the wire for cardinality.
     */
    @java.lang.Override public int getCardinalityValue() {
      return cardinality_;
    }
    /**
     * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
     * @param value The enum numeric value on the wire for cardinality to set.
     * @return This builder for chaining.
     */
    public Builder setCardinalityValue(int value) {
      cardinality_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
     * @return The cardinality.
     */
    @java.lang.Override
    public com.google.protobuf.Field.Cardinality getCardinality() {
      com.google.protobuf.Field.Cardinality result = com.google.protobuf.Field.Cardinality.forNumber(cardinality_);
      return result == null ? com.google.protobuf.Field.Cardinality.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
     * @param value The cardinality to set.
     * @return This builder for chaining.
     */
    public Builder setCardinality(com.google.protobuf.Field.Cardinality value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      cardinality_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Field.Cardinality cardinality = 2 [json_name = "cardinality"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCardinality() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cardinality_ = 0;
      onChanged();
      return this;
    }

    private int number_ ;
    /**
     * <code>int32 number = 3 [json_name = "number"];</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }
    /**
     * <code>int32 number = 3 [json_name = "number"];</code>
     * @param value The number to set.
     * @return This builder for chaining.
     */
    public Builder setNumber(int value) {

      number_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number = 3 [json_name = "number"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumber() {
      bitField0_ = (bitField0_ & ~0x00000004);
      number_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 4 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object typeUrl_ = "";
    /**
     * <code>string type_url = 6 [json_name = "typeUrl"];</code>
     * @return The typeUrl.
     */
    public java.lang.String getTypeUrl() {
      java.lang.Object ref = typeUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_url = 6 [json_name = "typeUrl"];</code>
     * @return The bytes for typeUrl.
     */
    public com.google.protobuf.ByteString
        getTypeUrlBytes() {
      java.lang.Object ref = typeUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_url = 6 [json_name = "typeUrl"];</code>
     * @param value The typeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setTypeUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      typeUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string type_url = 6 [json_name = "typeUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeUrl() {
      typeUrl_ = getDefaultInstance().getTypeUrl();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string type_url = 6 [json_name = "typeUrl"];</code>
     * @param value The bytes for typeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      typeUrl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int oneofIndex_ ;
    /**
     * <code>int32 oneof_index = 7 [json_name = "oneofIndex"];</code>
     * @return The oneofIndex.
     */
    @java.lang.Override
    public int getOneofIndex() {
      return oneofIndex_;
    }
    /**
     * <code>int32 oneof_index = 7 [json_name = "oneofIndex"];</code>
     * @param value The oneofIndex to set.
     * @return This builder for chaining.
     */
    public Builder setOneofIndex(int value) {

      oneofIndex_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 oneof_index = 7 [json_name = "oneofIndex"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofIndex() {
      bitField0_ = (bitField0_ & ~0x00000020);
      oneofIndex_ = 0;
      onChanged();
      return this;
    }

    private boolean packed_ ;
    /**
     * <code>bool packed = 8 [json_name = "packed"];</code>
     * @return The packed.
     */
    @java.lang.Override
    public boolean getPacked() {
      return packed_;
    }
    /**
     * <code>bool packed = 8 [json_name = "packed"];</code>
     * @param value The packed to set.
     * @return This builder for chaining.
     */
    public Builder setPacked(boolean value) {

      packed_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool packed = 8 [json_name = "packed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPacked() {
      bitField0_ = (bitField0_ & ~0x00000040);
      packed_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        options_ = new java.util.ArrayList<com.google.protobuf.Option>(options_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> optionsBuilder_;

    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 9 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private java.lang.Object jsonName_ = "";
    /**
     * <code>string json_name = 10 [json_name = "jsonName"];</code>
     * @return The jsonName.
     */
    public java.lang.String getJsonName() {
      java.lang.Object ref = jsonName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string json_name = 10 [json_name = "jsonName"];</code>
     * @return The bytes for jsonName.
     */
    public com.google.protobuf.ByteString
        getJsonNameBytes() {
      java.lang.Object ref = jsonName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string json_name = 10 [json_name = "jsonName"];</code>
     * @param value The jsonName to set.
     * @return This builder for chaining.
     */
    public Builder setJsonName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      jsonName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string json_name = 10 [json_name = "jsonName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonName() {
      jsonName_ = getDefaultInstance().getJsonName();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string json_name = 10 [json_name = "jsonName"];</code>
     * @param value The bytes for jsonName to set.
     * @return This builder for chaining.
     */
    public Builder setJsonNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      jsonName_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object defaultValue_ = "";
    /**
     * <code>string default_value = 11 [json_name = "defaultValue"];</code>
     * @return The defaultValue.
     */
    public java.lang.String getDefaultValue() {
      java.lang.Object ref = defaultValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        defaultValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string default_value = 11 [json_name = "defaultValue"];</code>
     * @return The bytes for defaultValue.
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      java.lang.Object ref = defaultValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        defaultValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string default_value = 11 [json_name = "defaultValue"];</code>
     * @param value The defaultValue to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      defaultValue_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string default_value = 11 [json_name = "defaultValue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDefaultValue() {
      defaultValue_ = getDefaultInstance().getDefaultValue();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string default_value = 11 [json_name = "defaultValue"];</code>
     * @param value The bytes for defaultValue to set.
     * @return This builder for chaining.
     */
    public Builder setDefaultValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      defaultValue_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Field)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Field)
  private static final com.google.protobuf.Field DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Field();
  }

  public static com.google.protobuf.Field getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Field>
      PARSER = new com.google.protobuf.AbstractParser<Field>() {
    @java.lang.Override
    public Field parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Field> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Field> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Field getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

