// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

public interface ListValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.ListValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .google.protobuf.Value values = 1 [json_name = "values"];</code>
   */
  java.util.List<com.google.protobuf.Value> 
      getValuesList();
  /**
   * <code>repeated .google.protobuf.Value values = 1 [json_name = "values"];</code>
   */
  com.google.protobuf.Value getValues(int index);
  /**
   * <code>repeated .google.protobuf.Value values = 1 [json_name = "values"];</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .google.protobuf.Value values = 1 [json_name = "values"];</code>
   */
  java.util.List<? extends com.google.protobuf.ValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Value values = 1 [json_name = "values"];</code>
   */
  com.google.protobuf.ValueOrBuilder getValuesOrBuilder(
      int index);
}
