// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/api.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Method}
 */
public final class Method extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Method)
    MethodOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Method.class.getName());
  }
  // Use Method.newBuilder() to construct.
  private Method(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Method() {
    name_ = "";
    requestTypeUrl_ = "";
    responseTypeUrl_ = "";
    options_ = java.util.Collections.emptyList();
    syntax_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.ApiProto.internal_static_google_protobuf_Method_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.ApiProto.internal_static_google_protobuf_Method_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Method.class, com.google.protobuf.Method.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_TYPE_URL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestTypeUrl_ = "";
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @return The requestTypeUrl.
   */
  @java.lang.Override
  public java.lang.String getRequestTypeUrl() {
    java.lang.Object ref = requestTypeUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestTypeUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
   * @return The bytes for requestTypeUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestTypeUrlBytes() {
    java.lang.Object ref = requestTypeUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestTypeUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_STREAMING_FIELD_NUMBER = 3;
  private boolean requestStreaming_ = false;
  /**
   * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
   * @return The requestStreaming.
   */
  @java.lang.Override
  public boolean getRequestStreaming() {
    return requestStreaming_;
  }

  public static final int RESPONSE_TYPE_URL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responseTypeUrl_ = "";
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @return The responseTypeUrl.
   */
  @java.lang.Override
  public java.lang.String getResponseTypeUrl() {
    java.lang.Object ref = responseTypeUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseTypeUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
   * @return The bytes for responseTypeUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseTypeUrlBytes() {
    java.lang.Object ref = responseTypeUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseTypeUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_STREAMING_FIELD_NUMBER = 5;
  private boolean responseStreaming_ = false;
  /**
   * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
   * @return The responseStreaming.
   */
  @java.lang.Override
  public boolean getResponseStreaming() {
    return responseStreaming_;
  }

  public static final int OPTIONS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int SYNTAX_FIELD_NUMBER = 7;
  private int syntax_ = 0;
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
   * @return The syntax.
   */
  @java.lang.Override public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestTypeUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, requestTypeUrl_);
    }
    if (requestStreaming_ != false) {
      output.writeBool(3, requestStreaming_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseTypeUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, responseTypeUrl_);
    }
    if (responseStreaming_ != false) {
      output.writeBool(5, responseStreaming_);
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(6, options_.get(i));
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(7, syntax_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestTypeUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestTypeUrl_);
    }
    if (requestStreaming_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, requestStreaming_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseTypeUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, responseTypeUrl_);
    }
    if (responseStreaming_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, responseStreaming_);
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, options_.get(i));
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, syntax_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Method)) {
      return super.equals(obj);
    }
    com.google.protobuf.Method other = (com.google.protobuf.Method) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getRequestTypeUrl()
        .equals(other.getRequestTypeUrl())) return false;
    if (getRequestStreaming()
        != other.getRequestStreaming()) return false;
    if (!getResponseTypeUrl()
        .equals(other.getResponseTypeUrl())) return false;
    if (getResponseStreaming()
        != other.getResponseStreaming()) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (syntax_ != other.syntax_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + REQUEST_TYPE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getRequestTypeUrl().hashCode();
    hash = (37 * hash) + REQUEST_STREAMING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRequestStreaming());
    hash = (37 * hash) + RESPONSE_TYPE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getResponseTypeUrl().hashCode();
    hash = (37 * hash) + RESPONSE_STREAMING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getResponseStreaming());
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    hash = (37 * hash) + SYNTAX_FIELD_NUMBER;
    hash = (53 * hash) + syntax_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Method parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Method parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Method parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Method parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Method parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Method parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Method parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Method prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.Method}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Method)
      com.google.protobuf.MethodOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.ApiProto.internal_static_google_protobuf_Method_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.ApiProto.internal_static_google_protobuf_Method_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Method.class, com.google.protobuf.Method.Builder.class);
    }

    // Construct using com.google.protobuf.Method.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      requestTypeUrl_ = "";
      requestStreaming_ = false;
      responseTypeUrl_ = "";
      responseStreaming_ = false;
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      syntax_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.ApiProto.internal_static_google_protobuf_Method_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Method getDefaultInstanceForType() {
      return com.google.protobuf.Method.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.protobuf.Method build() {
      com.google.protobuf.Method result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.protobuf.Method buildPartial() {
      com.google.protobuf.Method result = new com.google.protobuf.Method(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.protobuf.Method result) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.protobuf.Method result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestTypeUrl_ = requestTypeUrl_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.requestStreaming_ = requestStreaming_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.responseTypeUrl_ = responseTypeUrl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.responseStreaming_ = responseStreaming_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.syntax_ = syntax_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.Method) {
        return mergeFrom((com.google.protobuf.Method)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Method other) {
      if (other == com.google.protobuf.Method.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRequestTypeUrl().isEmpty()) {
        requestTypeUrl_ = other.requestTypeUrl_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getRequestStreaming() != false) {
        setRequestStreaming(other.getRequestStreaming());
      }
      if (!other.getResponseTypeUrl().isEmpty()) {
        responseTypeUrl_ = other.responseTypeUrl_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getResponseStreaming() != false) {
        setResponseStreaming(other.getResponseStreaming());
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000020);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (other.syntax_ != 0) {
        setSyntaxValue(other.getSyntaxValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              requestTypeUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              requestStreaming_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              responseTypeUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              responseStreaming_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              com.google.protobuf.Option m =
                  input.readMessage(
                      com.google.protobuf.Option.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 56: {
              syntax_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object requestTypeUrl_ = "";
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return The requestTypeUrl.
     */
    public java.lang.String getRequestTypeUrl() {
      java.lang.Object ref = requestTypeUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestTypeUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return The bytes for requestTypeUrl.
     */
    public com.google.protobuf.ByteString
        getRequestTypeUrlBytes() {
      java.lang.Object ref = requestTypeUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestTypeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @param value The requestTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestTypeUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestTypeUrl() {
      requestTypeUrl_ = getDefaultInstance().getRequestTypeUrl();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string request_type_url = 2 [json_name = "requestTypeUrl"];</code>
     * @param value The bytes for requestTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setRequestTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestTypeUrl_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean requestStreaming_ ;
    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @return The requestStreaming.
     */
    @java.lang.Override
    public boolean getRequestStreaming() {
      return requestStreaming_;
    }
    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @param value The requestStreaming to set.
     * @return This builder for chaining.
     */
    public Builder setRequestStreaming(boolean value) {

      requestStreaming_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool request_streaming = 3 [json_name = "requestStreaming"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestStreaming() {
      bitField0_ = (bitField0_ & ~0x00000004);
      requestStreaming_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object responseTypeUrl_ = "";
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return The responseTypeUrl.
     */
    public java.lang.String getResponseTypeUrl() {
      java.lang.Object ref = responseTypeUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseTypeUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return The bytes for responseTypeUrl.
     */
    public com.google.protobuf.ByteString
        getResponseTypeUrlBytes() {
      java.lang.Object ref = responseTypeUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseTypeUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @param value The responseTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTypeUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responseTypeUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseTypeUrl() {
      responseTypeUrl_ = getDefaultInstance().getResponseTypeUrl();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string response_type_url = 4 [json_name = "responseTypeUrl"];</code>
     * @param value The bytes for responseTypeUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResponseTypeUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseTypeUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean responseStreaming_ ;
    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @return The responseStreaming.
     */
    @java.lang.Override
    public boolean getResponseStreaming() {
      return responseStreaming_;
    }
    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @param value The responseStreaming to set.
     * @return This builder for chaining.
     */
    public Builder setResponseStreaming(boolean value) {

      responseStreaming_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool response_streaming = 5 [json_name = "responseStreaming"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseStreaming() {
      bitField0_ = (bitField0_ & ~0x00000010);
      responseStreaming_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        options_ = new java.util.ArrayList<com.google.protobuf.Option>(options_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> optionsBuilder_;

    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 6 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private int syntax_ = 0;
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override public int getSyntaxValue() {
      return syntax_;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      syntax_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return The syntax.
     */
    @java.lang.Override
    public com.google.protobuf.Syntax getSyntax() {
      com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
      return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      syntax_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 7 [json_name = "syntax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      bitField0_ = (bitField0_ & ~0x00000040);
      syntax_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Method)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Method)
  private static final com.google.protobuf.Method DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Method();
  }

  public static com.google.protobuf.Method getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Method>
      PARSER = new com.google.protobuf.AbstractParser<Method>() {
    @java.lang.Override
    public Method parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Method> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Method> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Method getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

