// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

public final class StructProto {
  private StructProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      StructProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Struct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Struct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Struct_FieldsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Struct_FieldsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_ListValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_ListValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034google/protobuf/struct.proto\022\017google.p" +
      "rotobuf\"\230\001\n\006Struct\022;\n\006fields\030\001 \003(\0132#.goo" +
      "gle.protobuf.Struct.FieldsEntryR\006fields\032" +
      "Q\n\013FieldsEntry\022\020\n\003key\030\001 \001(\tR\003key\022,\n\005valu" +
      "e\030\002 \001(\0132\026.google.protobuf.ValueR\005value:\002" +
      "8\001\"\262\002\n\005Value\022;\n\nnull_value\030\001 \001(\0162\032.googl" +
      "e.protobuf.NullValueH\000R\tnullValue\022#\n\014num" +
      "ber_value\030\002 \001(\001H\000R\013numberValue\022#\n\014string" +
      "_value\030\003 \001(\tH\000R\013stringValue\022\037\n\nbool_valu" +
      "e\030\004 \001(\010H\000R\tboolValue\022<\n\014struct_value\030\005 \001" +
      "(\0132\027.google.protobuf.StructH\000R\013structVal" +
      "ue\022;\n\nlist_value\030\006 \001(\0132\032.google.protobuf" +
      ".ListValueH\000R\tlistValueB\006\n\004kind\";\n\tListV" +
      "alue\022.\n\006values\030\001 \003(\0132\026.google.protobuf.V" +
      "alueR\006values*\033\n\tNullValue\022\016\n\nNULL_VALUE\020" +
      "\000B\177\n\023com.google.protobufB\013StructProtoP\001Z" +
      "/google.golang.org/protobuf/types/known/" +
      "structpb\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.Well" +
      "KnownTypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_Struct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_Struct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_Struct_descriptor,
        new java.lang.String[] { "Fields", });
    internal_static_google_protobuf_Struct_FieldsEntry_descriptor =
      internal_static_google_protobuf_Struct_descriptor.getNestedTypes().get(0);
    internal_static_google_protobuf_Struct_FieldsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_Struct_FieldsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_protobuf_Value_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_Value_descriptor,
        new java.lang.String[] { "NullValue", "NumberValue", "StringValue", "BoolValue", "StructValue", "ListValue", "Kind", });
    internal_static_google_protobuf_ListValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_ListValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_ListValue_descriptor,
        new java.lang.String[] { "Values", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
