// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/type.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Type}
 */
public final class Type extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Type)
    TypeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Type.class.getName());
  }
  // Use Type.newBuilder() to construct.
  private Type(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Type() {
    name_ = "";
    fields_ = java.util.Collections.emptyList();
    oneofs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    options_ = java.util.Collections.emptyList();
    syntax_ = 0;
    edition_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Type_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.TypeProto.internal_static_google_protobuf_Type_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Type.class, com.google.protobuf.Type.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Field> fields_;
  /**
   * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Field> getFieldsList() {
    return fields_;
  }
  /**
   * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.FieldOrBuilder> 
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
   */
  @java.lang.Override
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Field getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.FieldOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }

  public static final int ONEOFS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList oneofs_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
   * @return A list containing the oneofs.
   */
  public com.google.protobuf.ProtocolStringList
      getOneofsList() {
    return oneofs_;
  }
  /**
   * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
   * @return The count of oneofs.
   */
  public int getOneofsCount() {
    return oneofs_.size();
  }
  /**
   * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
   * @param index The index of the element to return.
   * @return The oneofs at the given index.
   */
  public java.lang.String getOneofs(int index) {
    return oneofs_.get(index);
  }
  /**
   * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the oneofs at the given index.
   */
  public com.google.protobuf.ByteString
      getOneofsBytes(int index) {
    return oneofs_.getByteString(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.protobuf.Option> options_;
  /**
   * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.Option> getOptionsList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 5;
  private com.google.protobuf.SourceContext sourceContext_;
  /**
   * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
   * @return Whether the sourceContext field is set.
   */
  @java.lang.Override
  public boolean hasSourceContext() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
   * @return The sourceContext.
   */
  @java.lang.Override
  public com.google.protobuf.SourceContext getSourceContext() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
    return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
  }

  public static final int SYNTAX_FIELD_NUMBER = 6;
  private int syntax_ = 0;
  /**
   * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
   * @return The syntax.
   */
  @java.lang.Override public com.google.protobuf.Syntax getSyntax() {
    com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
    return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
  }

  public static final int EDITION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object edition_ = "";
  /**
   * <code>string edition = 7 [json_name = "edition"];</code>
   * @return The edition.
   */
  @java.lang.Override
  public java.lang.String getEdition() {
    java.lang.Object ref = edition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      edition_ = s;
      return s;
    }
  }
  /**
   * <code>string edition = 7 [json_name = "edition"];</code>
   * @return The bytes for edition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEditionBytes() {
    java.lang.Object ref = edition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      edition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(2, fields_.get(i));
    }
    for (int i = 0; i < oneofs_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, oneofs_.getRaw(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(4, options_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(6, syntax_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(edition_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, edition_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, fields_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < oneofs_.size(); i++) {
        dataSize += computeStringSizeNoTag(oneofs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOneofsList().size();
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, options_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSourceContext());
    }
    if (syntax_ != com.google.protobuf.Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, syntax_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(edition_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, edition_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Type)) {
      return super.equals(obj);
    }
    com.google.protobuf.Type other = (com.google.protobuf.Type) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getFieldsList()
        .equals(other.getFieldsList())) return false;
    if (!getOneofsList()
        .equals(other.getOneofsList())) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (hasSourceContext() != other.hasSourceContext()) return false;
    if (hasSourceContext()) {
      if (!getSourceContext()
          .equals(other.getSourceContext())) return false;
    }
    if (syntax_ != other.syntax_) return false;
    if (!getEdition()
        .equals(other.getEdition())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    if (getOneofsCount() > 0) {
      hash = (37 * hash) + ONEOFS_FIELD_NUMBER;
      hash = (53 * hash) + getOneofsList().hashCode();
    }
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    if (hasSourceContext()) {
      hash = (37 * hash) + SOURCE_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSourceContext().hashCode();
    }
    hash = (37 * hash) + SYNTAX_FIELD_NUMBER;
    hash = (53 * hash) + syntax_;
    hash = (37 * hash) + EDITION_FIELD_NUMBER;
    hash = (53 * hash) + getEdition().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Type parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Type parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Type parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Type parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Type parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Type parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Type parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Type prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.Type}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Type)
      com.google.protobuf.TypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Type_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Type_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Type.class, com.google.protobuf.Type.Builder.class);
    }

    // Construct using com.google.protobuf.Type.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getFieldsFieldBuilder();
        getOptionsFieldBuilder();
        getSourceContextFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
      } else {
        fields_ = null;
        fieldsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      oneofs_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
      } else {
        options_ = null;
        optionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      sourceContext_ = null;
      if (sourceContextBuilder_ != null) {
        sourceContextBuilder_.dispose();
        sourceContextBuilder_ = null;
      }
      syntax_ = 0;
      edition_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.TypeProto.internal_static_google_protobuf_Type_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Type getDefaultInstanceForType() {
      return com.google.protobuf.Type.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.protobuf.Type build() {
      com.google.protobuf.Type result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.protobuf.Type buildPartial() {
      com.google.protobuf.Type result = new com.google.protobuf.Type(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.protobuf.Type result) {
      if (fieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.fields_ = fields_;
      } else {
        result.fields_ = fieldsBuilder_.build();
      }
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.protobuf.Type result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        oneofs_.makeImmutable();
        result.oneofs_ = oneofs_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.sourceContext_ = sourceContextBuilder_ == null
            ? sourceContext_
            : sourceContextBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.syntax_ = syntax_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.edition_ = edition_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.Type) {
        return mergeFrom((com.google.protobuf.Type)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Type other) {
      if (other == com.google.protobuf.Type.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (fieldsBuilder_ == null) {
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
      } else {
        if (!other.fields_.isEmpty()) {
          if (fieldsBuilder_.isEmpty()) {
            fieldsBuilder_.dispose();
            fieldsBuilder_ = null;
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000002);
            fieldsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getFieldsFieldBuilder() : null;
          } else {
            fieldsBuilder_.addAllMessages(other.fields_);
          }
        }
      }
      if (!other.oneofs_.isEmpty()) {
        if (oneofs_.isEmpty()) {
          oneofs_ = other.oneofs_;
          bitField0_ |= 0x00000004;
        } else {
          ensureOneofsIsMutable();
          oneofs_.addAll(other.oneofs_);
        }
        onChanged();
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000008);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (other.hasSourceContext()) {
        mergeSourceContext(other.getSourceContext());
      }
      if (other.syntax_ != 0) {
        setSyntaxValue(other.getSyntaxValue());
      }
      if (!other.getEdition().isEmpty()) {
        edition_ = other.edition_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.google.protobuf.Field m =
                  input.readMessage(
                      com.google.protobuf.Field.parser(),
                      extensionRegistry);
              if (fieldsBuilder_ == null) {
                ensureFieldsIsMutable();
                fields_.add(m);
              } else {
                fieldsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureOneofsIsMutable();
              oneofs_.add(s);
              break;
            } // case 26
            case 34: {
              com.google.protobuf.Option m =
                  input.readMessage(
                      com.google.protobuf.Option.parser(),
                      extensionRegistry);
              if (optionsBuilder_ == null) {
                ensureOptionsIsMutable();
                options_.add(m);
              } else {
                optionsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getSourceContextFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              syntax_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              edition_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Field> fields_ =
      java.util.Collections.emptyList();
    private void ensureFieldsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        fields_ = new java.util.ArrayList<com.google.protobuf.Field>(fields_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Field, com.google.protobuf.Field.Builder, com.google.protobuf.FieldOrBuilder> fieldsBuilder_;

    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public java.util.List<com.google.protobuf.Field> getFieldsList() {
      if (fieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fields_);
      } else {
        return fieldsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public int getFieldsCount() {
      if (fieldsBuilder_ == null) {
        return fields_.size();
      } else {
        return fieldsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public com.google.protobuf.Field getFields(int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);
      } else {
        return fieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder setFields(
        int index, com.google.protobuf.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder setFields(
        int index, com.google.protobuf.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder addFields(com.google.protobuf.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder addFields(
        int index, com.google.protobuf.Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(index, value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder addFields(
        com.google.protobuf.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder addFields(
        int index, com.google.protobuf.Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder addAllFields(
        java.lang.Iterable<? extends com.google.protobuf.Field> values) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
      } else {
        fieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder clearFields() {
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public Builder removeFields(int index) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.remove(index);
        onChanged();
      } else {
        fieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public com.google.protobuf.Field.Builder getFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public com.google.protobuf.FieldOrBuilder getFieldsOrBuilder(
        int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);  } else {
        return fieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public java.util.List<? extends com.google.protobuf.FieldOrBuilder> 
         getFieldsOrBuilderList() {
      if (fieldsBuilder_ != null) {
        return fieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fields_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public com.google.protobuf.Field.Builder addFieldsBuilder() {
      return getFieldsFieldBuilder().addBuilder(
          com.google.protobuf.Field.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public com.google.protobuf.Field.Builder addFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().addBuilder(
          index, com.google.protobuf.Field.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Field fields = 2 [json_name = "fields"];</code>
     */
    public java.util.List<com.google.protobuf.Field.Builder> 
         getFieldsBuilderList() {
      return getFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Field, com.google.protobuf.Field.Builder, com.google.protobuf.FieldOrBuilder> 
        getFieldsFieldBuilder() {
      if (fieldsBuilder_ == null) {
        fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Field, com.google.protobuf.Field.Builder, com.google.protobuf.FieldOrBuilder>(
                fields_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        fields_ = null;
      }
      return fieldsBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList oneofs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureOneofsIsMutable() {
      if (!oneofs_.isModifiable()) {
        oneofs_ = new com.google.protobuf.LazyStringArrayList(oneofs_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @return A list containing the oneofs.
     */
    public com.google.protobuf.ProtocolStringList
        getOneofsList() {
      oneofs_.makeImmutable();
      return oneofs_;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @return The count of oneofs.
     */
    public int getOneofsCount() {
      return oneofs_.size();
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param index The index of the element to return.
     * @return The oneofs at the given index.
     */
    public java.lang.String getOneofs(int index) {
      return oneofs_.get(index);
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the oneofs at the given index.
     */
    public com.google.protobuf.ByteString
        getOneofsBytes(int index) {
      return oneofs_.getByteString(index);
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param index The index to set the value at.
     * @param value The oneofs to set.
     * @return This builder for chaining.
     */
    public Builder setOneofs(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOneofsIsMutable();
      oneofs_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param value The oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addOneofs(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureOneofsIsMutable();
      oneofs_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param values The oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addAllOneofs(
        java.lang.Iterable<java.lang.String> values) {
      ensureOneofsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, oneofs_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofs() {
      oneofs_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string oneofs = 3 [json_name = "oneofs"];</code>
     * @param value The bytes of the oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addOneofsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureOneofsIsMutable();
      oneofs_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.google.protobuf.Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        options_ = new java.util.ArrayList<com.google.protobuf.Option>(options_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> optionsBuilder_;

    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder setOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder addOptions(com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder addOptions(
        com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder addOptions(
        int index, com.google.protobuf.Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends com.google.protobuf.Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public com.google.protobuf.OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public java.util.List<? extends com.google.protobuf.OptionOrBuilder> 
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public com.google.protobuf.Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, com.google.protobuf.Option.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.Option options = 4 [json_name = "options"];</code>
     */
    public java.util.List<com.google.protobuf.Option.Builder> 
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder> 
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.Option, com.google.protobuf.Option.Builder, com.google.protobuf.OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private com.google.protobuf.SourceContext sourceContext_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder> sourceContextBuilder_;
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     * @return Whether the sourceContext field is set.
     */
    public boolean hasSourceContext() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     * @return The sourceContext.
     */
    public com.google.protobuf.SourceContext getSourceContext() {
      if (sourceContextBuilder_ == null) {
        return sourceContext_ == null ? com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      } else {
        return sourceContextBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceContext_ = value;
      } else {
        sourceContextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public Builder setSourceContext(
        com.google.protobuf.SourceContext.Builder builderForValue) {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = builderForValue.build();
      } else {
        sourceContextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public Builder mergeSourceContext(com.google.protobuf.SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          sourceContext_ != null &&
          sourceContext_ != com.google.protobuf.SourceContext.getDefaultInstance()) {
          getSourceContextBuilder().mergeFrom(value);
        } else {
          sourceContext_ = value;
        }
      } else {
        sourceContextBuilder_.mergeFrom(value);
      }
      if (sourceContext_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public Builder clearSourceContext() {
      bitField0_ = (bitField0_ & ~0x00000010);
      sourceContext_ = null;
      if (sourceContextBuilder_ != null) {
        sourceContextBuilder_.dispose();
        sourceContextBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public com.google.protobuf.SourceContext.Builder getSourceContextBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getSourceContextFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    public com.google.protobuf.SourceContextOrBuilder getSourceContextOrBuilder() {
      if (sourceContextBuilder_ != null) {
        return sourceContextBuilder_.getMessageOrBuilder();
      } else {
        return sourceContext_ == null ?
            com.google.protobuf.SourceContext.getDefaultInstance() : sourceContext_;
      }
    }
    /**
     * <code>.google.protobuf.SourceContext source_context = 5 [json_name = "sourceContext"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder> 
        getSourceContextFieldBuilder() {
      if (sourceContextBuilder_ == null) {
        sourceContextBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.SourceContext, com.google.protobuf.SourceContext.Builder, com.google.protobuf.SourceContextOrBuilder>(
                getSourceContext(),
                getParentForChildren(),
                isClean());
        sourceContext_ = null;
      }
      return sourceContextBuilder_;
    }

    private int syntax_ = 0;
    /**
     * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override public int getSyntaxValue() {
      return syntax_;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      syntax_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
     * @return The syntax.
     */
    @java.lang.Override
    public com.google.protobuf.Syntax getSyntax() {
      com.google.protobuf.Syntax result = com.google.protobuf.Syntax.forNumber(syntax_);
      return result == null ? com.google.protobuf.Syntax.UNRECOGNIZED : result;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(com.google.protobuf.Syntax value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      syntax_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Syntax syntax = 6 [json_name = "syntax"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      bitField0_ = (bitField0_ & ~0x00000020);
      syntax_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object edition_ = "";
    /**
     * <code>string edition = 7 [json_name = "edition"];</code>
     * @return The edition.
     */
    public java.lang.String getEdition() {
      java.lang.Object ref = edition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        edition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string edition = 7 [json_name = "edition"];</code>
     * @return The bytes for edition.
     */
    public com.google.protobuf.ByteString
        getEditionBytes() {
      java.lang.Object ref = edition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        edition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string edition = 7 [json_name = "edition"];</code>
     * @param value The edition to set.
     * @return This builder for chaining.
     */
    public Builder setEdition(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      edition_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string edition = 7 [json_name = "edition"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEdition() {
      edition_ = getDefaultInstance().getEdition();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string edition = 7 [json_name = "edition"];</code>
     * @param value The bytes for edition to set.
     * @return This builder for chaining.
     */
    public Builder setEditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      edition_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Type)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Type)
  private static final com.google.protobuf.Type DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Type();
  }

  public static com.google.protobuf.Type getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Type>
      PARSER = new com.google.protobuf.AbstractParser<Type>() {
    @java.lang.Override
    public Type parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Type> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Type> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Type getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

