// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.27.2

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.Value}
 */
public final class Value extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Value)
    ValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Value.class.getName());
  }
  // Use Value.newBuilder() to construct.
  private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Value() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.StructProto.internal_static_google_protobuf_Value_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.StructProto.internal_static_google_protobuf_Value_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Value.class, com.google.protobuf.Value.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object kind_;
  public enum KindCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    NULL_VALUE(1),
    NUMBER_VALUE(2),
    STRING_VALUE(3),
    BOOL_VALUE(4),
    STRUCT_VALUE(5),
    LIST_VALUE(6),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return NULL_VALUE;
        case 2: return NUMBER_VALUE;
        case 3: return STRING_VALUE;
        case 4: return BOOL_VALUE;
        case 5: return STRUCT_VALUE;
        case 6: return LIST_VALUE;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int NULL_VALUE_FIELD_NUMBER = 1;
  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return Whether the nullValue field is set.
   */
  public boolean hasNullValue() {
    return kindCase_ == 1;
  }
  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return The enum numeric value on the wire for nullValue.
   */
  public int getNullValueValue() {
    if (kindCase_ == 1) {
      return (java.lang.Integer) kind_;
    }
    return 0;
  }
  /**
   * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
   * @return The nullValue.
   */
  public com.google.protobuf.NullValue getNullValue() {
    if (kindCase_ == 1) {
      com.google.protobuf.NullValue result = com.google.protobuf.NullValue.forNumber(
          (java.lang.Integer) kind_);
      return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
    }
    return com.google.protobuf.NullValue.NULL_VALUE;
  }

  public static final int NUMBER_VALUE_FIELD_NUMBER = 2;
  /**
   * <code>double number_value = 2 [json_name = "numberValue"];</code>
   * @return Whether the numberValue field is set.
   */
  @java.lang.Override
  public boolean hasNumberValue() {
    return kindCase_ == 2;
  }
  /**
   * <code>double number_value = 2 [json_name = "numberValue"];</code>
   * @return The numberValue.
   */
  @java.lang.Override
  public double getNumberValue() {
    if (kindCase_ == 2) {
      return (java.lang.Double) kind_;
    }
    return 0D;
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 3;
  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return Whether the stringValue field is set.
   */
  public boolean hasStringValue() {
    return kindCase_ == 3;
  }
  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return The stringValue.
   */
  public java.lang.String getStringValue() {
    java.lang.Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (kindCase_ == 3) {
        kind_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string string_value = 3 [json_name = "stringValue"];</code>
   * @return The bytes for stringValue.
   */
  public com.google.protobuf.ByteString
      getStringValueBytes() {
    java.lang.Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (kindCase_ == 3) {
        kind_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOOL_VALUE_FIELD_NUMBER = 4;
  /**
   * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
   * @return Whether the boolValue field is set.
   */
  @java.lang.Override
  public boolean hasBoolValue() {
    return kindCase_ == 4;
  }
  /**
   * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
   * @return The boolValue.
   */
  @java.lang.Override
  public boolean getBoolValue() {
    if (kindCase_ == 4) {
      return (java.lang.Boolean) kind_;
    }
    return false;
  }

  public static final int STRUCT_VALUE_FIELD_NUMBER = 5;
  /**
   * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
   * @return Whether the structValue field is set.
   */
  @java.lang.Override
  public boolean hasStructValue() {
    return kindCase_ == 5;
  }
  /**
   * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
   * @return The structValue.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getStructValue() {
    if (kindCase_ == 5) {
       return (com.google.protobuf.Struct) kind_;
    }
    return com.google.protobuf.Struct.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getStructValueOrBuilder() {
    if (kindCase_ == 5) {
       return (com.google.protobuf.Struct) kind_;
    }
    return com.google.protobuf.Struct.getDefaultInstance();
  }

  public static final int LIST_VALUE_FIELD_NUMBER = 6;
  /**
   * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
   * @return Whether the listValue field is set.
   */
  @java.lang.Override
  public boolean hasListValue() {
    return kindCase_ == 6;
  }
  /**
   * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
   * @return The listValue.
   */
  @java.lang.Override
  public com.google.protobuf.ListValue getListValue() {
    if (kindCase_ == 6) {
       return (com.google.protobuf.ListValue) kind_;
    }
    return com.google.protobuf.ListValue.getDefaultInstance();
  }
  /**
   * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.ListValueOrBuilder getListValueOrBuilder() {
    if (kindCase_ == 6) {
       return (com.google.protobuf.ListValue) kind_;
    }
    return com.google.protobuf.ListValue.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeEnum(1, ((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      output.writeDouble(
          2, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 3) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, kind_);
    }
    if (kindCase_ == 4) {
      output.writeBool(
          4, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 5) {
      output.writeMessage(5, (com.google.protobuf.Struct) kind_);
    }
    if (kindCase_ == 6) {
      output.writeMessage(6, (com.google.protobuf.ListValue) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ((java.lang.Integer) kind_));
    }
    if (kindCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(
            2, (double)((java.lang.Double) kind_));
    }
    if (kindCase_ == 3) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, kind_);
    }
    if (kindCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(
            4, (boolean)((java.lang.Boolean) kind_));
    }
    if (kindCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.google.protobuf.Struct) kind_);
    }
    if (kindCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.google.protobuf.ListValue) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Value)) {
      return super.equals(obj);
    }
    com.google.protobuf.Value other = (com.google.protobuf.Value) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (getNullValueValue()
            != other.getNullValueValue()) return false;
        break;
      case 2:
        if (java.lang.Double.doubleToLongBits(getNumberValue())
            != java.lang.Double.doubleToLongBits(
                other.getNumberValue())) return false;
        break;
      case 3:
        if (!getStringValue()
            .equals(other.getStringValue())) return false;
        break;
      case 4:
        if (getBoolValue()
            != other.getBoolValue()) return false;
        break;
      case 5:
        if (!getStructValue()
            .equals(other.getStructValue())) return false;
        break;
      case 6:
        if (!getListValue()
            .equals(other.getListValue())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + NULL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNullValueValue();
        break;
      case 2:
        hash = (37 * hash) + NUMBER_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getNumberValue()));
        break;
      case 3:
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
        break;
      case 4:
        hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getBoolValue());
        break;
      case 5:
        hash = (37 * hash) + STRUCT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStructValue().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LIST_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getListValue().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Value parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Value parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Value parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Value parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Value prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.Value}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Value)
      com.google.protobuf.ValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.StructProto.internal_static_google_protobuf_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.StructProto.internal_static_google_protobuf_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Value.class, com.google.protobuf.Value.Builder.class);
    }

    // Construct using com.google.protobuf.Value.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (structValueBuilder_ != null) {
        structValueBuilder_.clear();
      }
      if (listValueBuilder_ != null) {
        listValueBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.StructProto.internal_static_google_protobuf_Value_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Value getDefaultInstanceForType() {
      return com.google.protobuf.Value.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.protobuf.Value build() {
      com.google.protobuf.Value result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.protobuf.Value buildPartial() {
      com.google.protobuf.Value result = new com.google.protobuf.Value(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.protobuf.Value result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.protobuf.Value result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 5 &&
          structValueBuilder_ != null) {
        result.kind_ = structValueBuilder_.build();
      }
      if (kindCase_ == 6 &&
          listValueBuilder_ != null) {
        result.kind_ = listValueBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.Value) {
        return mergeFrom((com.google.protobuf.Value)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Value other) {
      if (other == com.google.protobuf.Value.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case NULL_VALUE: {
          setNullValueValue(other.getNullValueValue());
          break;
        }
        case NUMBER_VALUE: {
          setNumberValue(other.getNumberValue());
          break;
        }
        case STRING_VALUE: {
          kindCase_ = 3;
          kind_ = other.kind_;
          onChanged();
          break;
        }
        case BOOL_VALUE: {
          setBoolValue(other.getBoolValue());
          break;
        }
        case STRUCT_VALUE: {
          mergeStructValue(other.getStructValue());
          break;
        }
        case LIST_VALUE: {
          mergeListValue(other.getListValue());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              kindCase_ = 1;
              kind_ = rawValue;
              break;
            } // case 8
            case 17: {
              kind_ = input.readDouble();
              kindCase_ = 2;
              break;
            } // case 17
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              kindCase_ = 3;
              kind_ = s;
              break;
            } // case 26
            case 32: {
              kind_ = input.readBool();
              kindCase_ = 4;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getStructValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getListValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private java.lang.Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @return Whether the nullValue field is set.
     */
    @java.lang.Override
    public boolean hasNullValue() {
      return kindCase_ == 1;
    }
    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @return The enum numeric value on the wire for nullValue.
     */
    @java.lang.Override
    public int getNullValueValue() {
      if (kindCase_ == 1) {
        return ((java.lang.Integer) kind_).intValue();
      }
      return 0;
    }
    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @param value The enum numeric value on the wire for nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValueValue(int value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @return The nullValue.
     */
    @java.lang.Override
    public com.google.protobuf.NullValue getNullValue() {
      if (kindCase_ == 1) {
        com.google.protobuf.NullValue result = com.google.protobuf.NullValue.forNumber(
            (java.lang.Integer) kind_);
        return result == null ? com.google.protobuf.NullValue.UNRECOGNIZED : result;
      }
      return com.google.protobuf.NullValue.NULL_VALUE;
    }
    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @param value The nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValue(com.google.protobuf.NullValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      kindCase_ = 1;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.NullValue null_value = 1 [json_name = "nullValue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNullValue() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>double number_value = 2 [json_name = "numberValue"];</code>
     * @return Whether the numberValue field is set.
     */
    public boolean hasNumberValue() {
      return kindCase_ == 2;
    }
    /**
     * <code>double number_value = 2 [json_name = "numberValue"];</code>
     * @return The numberValue.
     */
    public double getNumberValue() {
      if (kindCase_ == 2) {
        return (java.lang.Double) kind_;
      }
      return 0D;
    }
    /**
     * <code>double number_value = 2 [json_name = "numberValue"];</code>
     * @param value The numberValue to set.
     * @return This builder for chaining.
     */
    public Builder setNumberValue(double value) {

      kindCase_ = 2;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double number_value = 2 [json_name = "numberValue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberValue() {
      if (kindCase_ == 2) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @return Whether the stringValue field is set.
     */
    @java.lang.Override
    public boolean hasStringValue() {
      return kindCase_ == 3;
    }
    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @return The stringValue.
     */
    @java.lang.Override
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (kindCase_ == 3) {
          kind_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @return The bytes for stringValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (kindCase_ == 3) {
          kind_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      if (kindCase_ == 3) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string string_value = 3 [json_name = "stringValue"];</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
     * @return Whether the boolValue field is set.
     */
    public boolean hasBoolValue() {
      return kindCase_ == 4;
    }
    /**
     * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
     * @return The boolValue.
     */
    public boolean getBoolValue() {
      if (kindCase_ == 4) {
        return (java.lang.Boolean) kind_;
      }
      return false;
    }
    /**
     * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {

      kindCase_ = 4;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool bool_value = 4 [json_name = "boolValue"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      if (kindCase_ == 4) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> structValueBuilder_;
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     * @return Whether the structValue field is set.
     */
    @java.lang.Override
    public boolean hasStructValue() {
      return kindCase_ == 5;
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     * @return The structValue.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getStructValue() {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5) {
          return (com.google.protobuf.Struct) kind_;
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      } else {
        if (kindCase_ == 5) {
          return structValueBuilder_.getMessage();
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    public Builder setStructValue(com.google.protobuf.Struct value) {
      if (structValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        structValueBuilder_.setMessage(value);
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    public Builder setStructValue(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (structValueBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        structValueBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    public Builder mergeStructValue(com.google.protobuf.Struct value) {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5 &&
            kind_ != com.google.protobuf.Struct.getDefaultInstance()) {
          kind_ = com.google.protobuf.Struct.newBuilder((com.google.protobuf.Struct) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 5) {
          structValueBuilder_.mergeFrom(value);
        } else {
          structValueBuilder_.setMessage(value);
        }
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    public Builder clearStructValue() {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
        }
        structValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    public com.google.protobuf.Struct.Builder getStructValueBuilder() {
      return getStructValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getStructValueOrBuilder() {
      if ((kindCase_ == 5) && (structValueBuilder_ != null)) {
        return structValueBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 5) {
          return (com.google.protobuf.Struct) kind_;
        }
        return com.google.protobuf.Struct.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.Struct struct_value = 5 [json_name = "structValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getStructValueFieldBuilder() {
      if (structValueBuilder_ == null) {
        if (!(kindCase_ == 5)) {
          kind_ = com.google.protobuf.Struct.getDefaultInstance();
        }
        structValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                (com.google.protobuf.Struct) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 5;
      onChanged();
      return structValueBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder, com.google.protobuf.ListValueOrBuilder> listValueBuilder_;
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     * @return Whether the listValue field is set.
     */
    @java.lang.Override
    public boolean hasListValue() {
      return kindCase_ == 6;
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     * @return The listValue.
     */
    @java.lang.Override
    public com.google.protobuf.ListValue getListValue() {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6) {
          return (com.google.protobuf.ListValue) kind_;
        }
        return com.google.protobuf.ListValue.getDefaultInstance();
      } else {
        if (kindCase_ == 6) {
          return listValueBuilder_.getMessage();
        }
        return com.google.protobuf.ListValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    public Builder setListValue(com.google.protobuf.ListValue value) {
      if (listValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        listValueBuilder_.setMessage(value);
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    public Builder setListValue(
        com.google.protobuf.ListValue.Builder builderForValue) {
      if (listValueBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        listValueBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    public Builder mergeListValue(com.google.protobuf.ListValue value) {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6 &&
            kind_ != com.google.protobuf.ListValue.getDefaultInstance()) {
          kind_ = com.google.protobuf.ListValue.newBuilder((com.google.protobuf.ListValue) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 6) {
          listValueBuilder_.mergeFrom(value);
        } else {
          listValueBuilder_.setMessage(value);
        }
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    public Builder clearListValue() {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 6) {
          kindCase_ = 0;
          kind_ = null;
        }
        listValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    public com.google.protobuf.ListValue.Builder getListValueBuilder() {
      return getListValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.ListValueOrBuilder getListValueOrBuilder() {
      if ((kindCase_ == 6) && (listValueBuilder_ != null)) {
        return listValueBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 6) {
          return (com.google.protobuf.ListValue) kind_;
        }
        return com.google.protobuf.ListValue.getDefaultInstance();
      }
    }
    /**
     * <code>.google.protobuf.ListValue list_value = 6 [json_name = "listValue"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder, com.google.protobuf.ListValueOrBuilder> 
        getListValueFieldBuilder() {
      if (listValueBuilder_ == null) {
        if (!(kindCase_ == 6)) {
          kind_ = com.google.protobuf.ListValue.getDefaultInstance();
        }
        listValueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.ListValue, com.google.protobuf.ListValue.Builder, com.google.protobuf.ListValueOrBuilder>(
                (com.google.protobuf.ListValue) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 6;
      onChanged();
      return listValueBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Value)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Value)
  private static final com.google.protobuf.Value DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Value();
  }

  public static com.google.protobuf.Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Value>
      PARSER = new com.google.protobuf.AbstractParser<Value>() {
    @java.lang.Override
    public Value parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Value> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Value> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Value getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

